# -*- coding: utf-8 -*-
"""Invoice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ShJdBsCNrsElUj8rQijU6X5tZ8qj6zez
"""

import streamlit as st
import pandas as pd
from io import StringIO

def generate_iif(df):
    output = StringIO()

    # Write headers
    output.write("!TRNS\tTRNSTYPE\tDATE\tACCNT\tNAME\tMEMO\tAMOUNT\tDOCNUM\n")
    output.write("!SPL\tTRNSTYPE\tDATE\tACCNT\tNAME\tMEMO\tAMOUNT\n")
    output.write("!ENDTRNS\n")  # As required on third line

    # Remove voided items
    df = df[~df['Type'].str.lower().str.contains("void")]

    # Group by Bill# to process each transaction
    for bill_no, bill_df in df.groupby('Bill#'):
        trans_date = pd.to_datetime(bill_df['Trans Date'].iloc[0])
        date_str = trans_date.strftime('%m/%d/%Y')
        day = trans_date.day
        till = bill_df['Till#'].iloc[0]
        customer = "POS Customer"
        memo = f"Till {till} Bill {bill_no}"
        docnum = f"INV{day:02d}/{int(bill_no):02d}"

        # Determine if it's a return
        is_return = all(bill_df['Type'].str.lower() == 'return')
        trnstype = "CREDIT MEMO" if is_return else "INVOICE"

        # Sum total and reverse sign for QB import
        total_amount = -bill_df['Total'].sum()

        # TRNS header
        output.write(f"TRNS\t{trnstype}\t{date_str}\tAccounts Receivable\t{customer}\t{memo}\t{total_amount:.2f}\t{docnum}\n")

        # SPL lines
        for _, row in bill_df.iterrows():
            desc = row['Description']
            item_code = row['Code']
            amount = -row['Total']  # Reverse sign for QB
            output.write(f"SPL\t{trnstype}\t{date_str}\tRevenue:Sales\t{customer}\t{desc} ({item_code})\t{amount:.2f}\n")

        # ENDTRNS per transaction
        output.write("ENDTRNS\n")

    return output.getvalue()

# --- Streamlit UI ---
st.set_page_config(page_title="QuickBooks IIF Converter", layout="wide")
st.title("🧾 QuickBooks Invoice & Credit Memo IIF Generator")

uploaded_file = st.file_uploader("📤 Upload your POS CSV file", type=["csv"])

if uploaded_file:
    try:
        df = pd.read_csv(uploaded_file, sep=None, engine='python')
        st.success("✅ File uploaded and parsed successfully.")

        st.subheader("📋 Data Preview")
        st.dataframe(df)

        if st.button("🚀 Generate QuickBooks IIF"):
            iif_output = generate_iif(df)
            st.download_button(
                label="📥 Download .IIF File",
                data=iif_output,
                file_name="qb_sales_import.iif",
                mime="text/plain"
            )
    except Exception as e:
        st.error(f"❌ Error processing file: {e}")